version: 2.1

jobs:
  check_gyms:
    docker:
      - image: hisa9chi/ruby-chromedriver:2.7.4
    resource_class: small
    steps:
      - checkout
      - run:
          name: bundle install
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle config set --local without 'development' 
            bundle install
      - run:
          name: Check Available Gyms
          command: bundle exec ruby script.rb
      - store_artifacts:
          path: ./result

workflows:
  version: 2
  check_gym_availables:
    triggers:
      - schedule:
          cron: "30 0-14 * * *" # UTC ( JST = UTC+0900 9:30 - 23:30 )
          filters:
            branches:
              only:
                - main
    jobs:
      - check_gyms
  push_check_job:
    jobs:
      - check_gyms
