---
login_url: "https://www.fureai-net.city.kawasaki.jp/web/index.jsp"

user:
  id: <%= ENV['KAWASAKI_USER_ID'] %>
  pass: <%= ENV['KAWASAKI_USER_PASS'] %>

gym:
  # 平日夜間 + 休日全日程 チェック対象
  all_day:
    - 'カルッツかわさき'
  # 休日全日程 チェック対象
  day_off:
    - '幸スポーツセンター'
    - '麻生スポーツセンター'
# 以下駅から遠いので除外
#    - 'とどろきアリーナ'
#    - '高津スポーツセンター'
#    - '川崎市民プラザ'
#    - '川崎マリエン'
#    - '宮前スポーツセンター'
#    - '川崎市多摩スポーツセンター'
